### ISSUE TITLE
Application crashes if there are a lot of replays

### ISSUE THREAD

**Issue by alexsharoff** [temtan/ggxxacpr_replay_organizer#1]
I have approximately 10000 replays. After ggxxacpr_replay_organizer.exe asks "Automatically configure replay folder settings and your username. Is it OK?" and I click OK, it crashes most of the time. If I try multiple times it succeeds after 3-5 attempts.

If I move most of the replays out `%USERPROFILE%\Documents\ARC SYSTEM WORKS\GGXXAC\Replays`, leaving only 200 of them, it stops crashing.

If it's at all helpful, I looked at the error under debugger a little bit. It's a read access violation in base.cpp:241 (`if ( *current != L'(' ) {`). Each error happened when parsing a different replay for me (`replay_file` was always different).

**Comment by temtan** [comment]
その症状はバッファーオーバーラン等の不正ポインタ操作でしょう。
指摘された箇所のソースを少しだけ確認しましたが、今は問題無いように見えます。また後で確認してみます。
自分の環境でも約10000のリプレイファイルがありますが、その症状は出ていません。
恐らくリプレイファイルの数ではなく、特定のリプレイファイルのファイル名でそのような事が時々起きるのかもしれません。
もしもその症状が出るファイル名が判るのならば、この不具合対処の方法が判るかも知れません。

The symptom would be an illegal pointer operation such as a buffer overrun.
I just checked the source of the point you pointed out, and it looks like there is no problem now. I'll check again later.
I have about 10,000 replay files in my environment, but I haven't had any of these symptoms.
Maybe this happens sometimes with the file name of a particular replay file, rather than the number of replay files.
If you can find the name of the file that causes this problem, you may be able to find a way to deal with this problem.

**Comment by temtan** [comment]
リプレイファイルのファイル名が正常ではない時にバッファーオーバーランする可能性がある事が判りました。
これに対処しても alexsharoff さんの言う問題が直るかどうかは判りませんが、
修正して1.0.1としてリリースする予定ですので、それまでお待ち下さい。

It has been found that a buffer overrun may occur when the replay file name is incorrect.
I don't know if dealing with this will fix the problem that Alexsharoff mentions, but
We are planning to fix it and release it as 1.0.1, so please wait until then.

**Comment by alexsharoff** [comment]
Version 1.0.1 doesn't crash anymore for me. Thank you.
